version: '3.8'
services:
  app:
    build:
      context: .
    container_name: consulter-prect-app
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: consulter-prect-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
